### ISSUE TITLE
Handle python dependency installation

### ISSUE THREAD

**Issue by ebrahimebrahim** [stephencrowell/SlicerEHRSandbox#1]
Currently (and this is referring to the [display-patient-and-observation](https://github.com/stephencrowell/fhir-slicer-extension/tree/display-patient-and-observation) branch) when I add the module to Slicer, the module fails to load with the following error:

```txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ebrahim/Downloads/Slicer-5.1.0-2022-07-17-linux-amd64/lib/Python/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ebrahim/fhir-slicer-extension/FHIRReader/FHIRReader/FHIRReader.py", line 11, in <module>
    from fhirclient import client
ModuleNotFoundError: No module named 'fhirclient'
```

Not surprising-- I haven't installed fhirclient. This will go away when I install it.

But we need to include installing the dependency in a more elegant way and not require the user to fiddle with the python console.

I don't know if this is the best way, but here is an example of what I did in the lungair module:
- [Try an import and redirect the import failure message to an error message informing the user that they should install python dependencies and restart the application.](https://github.com/KitwareMedical/lungair-desktop-application/blob/b595637cdaee06092ede4f0ef2ea38d777f8c5f2/Modules/Scripted/Home/Home.py#L471-L482)
- [Include a button that installs the needed dependency](https://github.com/KitwareMedical/lungair-desktop-application/blob/b595637cdaee06092ede4f0ef2ea38d777f8c5f2/Modules/Scripted/Home/Home.py#L115-L119)
- Feel free to copy [dependency installer](https://github.com/KitwareMedical/lungair-desktop-application/blob/b595637cdaee06092ede4f0ef2ea38d777f8c5f2/Modules/Scripted/Home/HomeLib/dependency_installer.py) which handles checking whether a package is installed, doing the installation if not, and reporting errors nicely. We'd just get rid of [this stuff](https://github.com/KitwareMedical/lungair-desktop-application/blob/b595637cdaee06092ede4f0ef2ea38d777f8c5f2/Modules/Scripted/Home/HomeLib/dependency_installer.py#L59-L73) and define something like `check_and_install_fhirclient = functools.partial(check_and_install_package, ["fhirclient"], "fhirclient")`. Also since you are using `BusyCursor` in `FHIRReader.py` then it makes sense to move it to some common utility library that both `FHIRReader.py` and `dependency_installer.py` can use.

**Comment by stephencrowell** [comment]
> * Try an import and redirect the import failure message to an error message informing the user that they should install python dependencies and restart the application.

Is it fine if this warning comes up when launching slicer? I want to keep the imports at the global level so we don't have to constantly import them. I am able to disable to `Load Patients` button and the user can still interact with the install button.

**Comment by ebrahimebrahim** [comment]
Yes this makes sense. This is the approach the lungair application takes, sort of. It gives a warning message on launch like "hey just so you know this won't work until you install blah blah dependencies; please install them and restart the application"

edit: and it's also nice if the warning message can point you to the button that does the installation
