### ISSUE TITLE
get rid of the plot chart pin button

### ISSUE THREAD

**Issue by ebrahimebrahim** [stephencrowell/SlicerEHRSandbox#2]
![image](https://user-images.githubusercontent.com/1879759/201738592-bf3040a2-7344-431e-be40-69a0e8218669.png)

This pin button is showing plot chart buttons because among the possible types of [vtkMRMLAbstractViewNode](https://apidocs.slicer.org/master/classvtkMRMLAbstractViewNode.html), these [are vtkMRMLPlotViewNodes](https://github.com/stephencrowell/fhir-slicer-extension/blob/e98fc679e9a13b267edbe7d9d85cd905a97b1f8f/FHIRReader/FHIRReader/Resources/fhir-layout.xml#L3).

One approach is to hide the pin button like we [did with lungair here](https://github.com/KitwareMedical/lungair-desktop-application/blob/b595637cdaee06092ede4f0ef2ea38d777f8c5f2/Modules/Scripted/Home/Home.py#L407).

**Comment by ebrahimebrahim** [comment]
Also why are we using vtkMRMLPlotViewNodes and injecting tables into them rather than using vtkMRMLTableViewNodes?

Then we wouldn't have to create our own [qMRMLTableView](https://github.com/stephencrowell/fhir-slicer-extension/blob/e98fc679e9a13b267edbe7d9d85cd905a97b1f8f/FHIRReader/FHIRReader/FHIRReader.py#L407) and inject it into the widget, but could instead use the `vtkMRMLTableViewNode` API for doing that. IDK if that's better or worse, just throwing it out there as something to consider.

**Comment by stephencrowell** [comment]
> Also why are we using vtkMRMLPlotViewNodes and injecting tables into them rather than using vtkMRMLTableViewNodes?

Mostly a lack of understanding of how Slicer worked. I was planning on changing the code away from the lungair copy and paste, but got sidetracked and forgot.
