### ISSUE TITLE
add correct description material throughout extension and repo

### ISSUE THREAD

**Issue by ebrahimebrahim** [stephencrowell/SlicerEHRSandbox#3]
Currently we are still using all the default extension metadata and we have a placeholder project name; we should

- [x] Name the extension; the name should be SlicerSomething. Maybe SlicerEHRSandbox or something like that.
- [x] Rename the repo accordingly (SlicerSomething) and give it the tags "lungair" and "3d-slicer-extension"
- [x] Put in the extension and module metadata a brief description, reference to the contributors (stephen, ebrahim, andinet) and acknowledgement of the grant (NIH award R42HL145669).
- [x] Create an icon for the extension and for the module
- [x] Choose the correct category for this extension (currently it's the default "Examples")
- ~~[ ] Package the application, creating a tagged commit and release object~~ No need to actually do this yet, but I created #19 to track ensuring that we are able to create a package when we are ready to make a release.
- [x] Put some more info in the readme about how to install and use the extension. We should probably link up to [lungair-fhir-server](https://github.com/KitwareMedical/lungair-fhir-server) and perhaps rename that repo accordingly
- [x] Move this repo to KitwareMedical and give it the tag "kitware"

**Comment by stephencrowell** [comment]
> * Choose the correct category for this extension (currently it's the default "Examples")

Is there a specific category we had in mind? I was thinking either `Data` or `Web System Tools`.

**Comment by ebrahimebrahim** [comment]
How about `Informatics`?

(Is that what you meant when you said `Data`? I don't see a `Data` category)

**Comment by stephencrowell** [comment]
Sorry I meant `Informatics`. Data is one of the options inside and I mixed them up.

**Comment by ebrahimebrahim** [comment]
Regarding the creation of a release object, I have asked a question here: https://discourse.slicer.org/t/how-to-release-an-extension/26289

**Comment by ebrahimebrahim** [comment]
> Put in the extension and module metadata a brief description, reference to the contributors

put full names of contributors and make the grant acknowledgement similar to the one at the end of the [lungair](https://github.com/KitwareMedical/lungair-desktop-application) readme.

**Comment by ebrahimebrahim** [comment]
> Name the extension

don't forget to propagate the name change into the readme

**Comment by ebrahimebrahim** [comment]
> Rename the repo accordingly (SlicerSomething) and give it the tags "lungair" and "3d-slicer-extension"

still needs the ~~tag~~topic "lungair"

**Comment by jcfr** [comment]
README could be further improved inspiring from the following extension(s):
* https://github.com/kitwaremedical/SlicerPipelines

**Comment by ebrahimebrahim** [comment]
with the transfer to KitwareMedical this is now complete :tada:
