### ISSUE TITLE
patient/obs widgets don't interact well with the rest of slicer

### ISSUE THREAD

**Issue by ebrahimebrahim** [stephencrowell/SlicerEHRSandbox#4]
Currently (and this is referring to [display-patient-and-observation](https://github.com/stephencrowell/fhir-slicer-extension/tree/display-patient-and-observation) branch) if we switch to the FHIRReader module then the current layout is replaced by the layout that shows the patient/obs widgets. If I then want to use the slice views then I can do that by changing the layout, e.g. View -> Layout -> Four-Up. Once I do that there seems to be no way to get the patient/obs widgets back, not even by switching out of and back into the FHIRReader module. There are really two issues here:

1. (Broken behavior) If we switch into FHIRReader module then change the layout manually, then there's seems to be no way to recover the FHIRReader module's initial layout.
2. (Inconvenient behavior) If we switch into FHIRReader module then our layout is replaced, but switching out of FHIRReader module doesn't revert the layout to what we had before. That's a bit annoying. Not sure how to deal with it.
  a. I wonder if we can switch to something more like how the DICOM browser works, where it just lets you toggle between viewing a dicom data display widget versus the usual underlying layout on the right side.
  b. Probably this is not the first time someone deals with this so it's worth looking into other solutions before complicating things too much.

**Comment by ebrahimebrahim** [comment]
Layout documentation might help somewhere: https://slicer.readthedocs.io/en/latest/developer_guide/mrml_overview.html#layout

**Comment by ebrahimebrahim** [comment]
Got some advice that can help us here (thank you @sjh26 and @jcfr):

The `ScriptedLoadableModuleWidget` has a `setup` function where we are currently setting up the widgets, and this causes problem (1) above because `setup` is just called once when you enter the module for the first time.

There are also `enter` and `exit` functions which are called when you switch into and out of the module respectively.

If we move our layout initialization into the `enter` function then this should solve problem (1).

If we also record the current layout ID in `enter` then we should be able to revert to the previous layout in `exit`. This would solve (2).

**Comment by ebrahimebrahim** [comment]
If we did want to do something more like what's in the dicom browser...

https://github.com/Slicer/Slicer/blob/9fae00686d071642a74b57a2e9cd2280aeccc177/Modules/Scripted/DICOM/DICOM.py#L787

That's the function that gets called when you toggle this "show dicom database" button:

![image](https://user-images.githubusercontent.com/1879759/201753689-e41b4749-e530-4106-ac09-8835e8d7e5bd.png)

I'm not fully understanding how this works but it's a place to start looking

**Comment by stephencrowell** [comment]
If we are able to save the FHIRReader layout (based off 3rd comment it should be possible), what do we gain by going the DICOM browser route? The main advantage I can see is when the reader starts interacting with DICOM images (in this case, we have table view and then normal slicer view for images).

**Comment by ebrahimebrahim** [comment]
The DICOM browser, I _think_, seems to not do the hacky thing we are doing in which we grab a vtkMRMLPlotViewNode and inject our own stuff into it. But IDK if this matters. Feel free to ignore the dicom browser approach for now, I just wanted to include a note on it in case we later decide that we need that approach.

**Comment by stephencrowell** [comment]
I had a thought while working on #9 yesterday. Should we be initialing the layout every time we `enter`? If we save the layout ID for the extension, can't we just set the layout to ID and then only initialize once? #9 has an issue where whenever we switch between different modules we create new TableNodes and I was wondering if this could be part of the reason.
