### ISSUE TITLE
url needs trailing slash to work

### ISSUE THREAD

**Issue by ebrahimebrahim** [stephencrowell/SlicerEHRSandbox#5]
Because of the way of combining URL components [here](https://github.com/stephencrowell/fhir-slicer-extension/blob/e98fc679e9a13b267edbe7d9d85cd905a97b1f8f/FHIRReader/FHIRReader/FHIRReader.py#L439), it took me a while to figure out that this fails:
![image](https://user-images.githubusercontent.com/1879759/201755197-71cbf012-a61a-4367-b1fe-bdc5f0c8654d.png)
due to the lack of a trailing `/`

consider using https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin

**Comment by stephencrowell** [comment]
Does `urljoin` work this way?  I thought `urljoin` took the base from the first url and appended the second url to that. In our case, the 'hapi=fhir-jpaserver' isn't part of the base. 

We could append the entire '/hapi-fhir-jpaserver/fhir/' to the URL and then `urljoin` will work the way we want. Is '/hapi-fhir-jpaserver/fhir/' consistent for any FHIR server or is it just the way our is configured?

**Comment by ebrahimebrahim** [comment]
Hmm good point

- we could just add the trailing `/` in code if it is not there
- why is the input for FHIR Server `http://localhost:4004/hapi-fhir-jpaserver/` anyway? why not `http://localhost:4004` or `http://localhost:4004/hapi-fhir-jpaserver/fhir` or even `localhost:4004`? I am not actually sure what we can assume about one's FHIR server setup ... any thouhgts on this? if we don't know then we can just make the expected input be the full `http://localhost:4004/hapi-fhir-jpaserver/fhir` since that seems to be what the smart api wants to see

**Comment by stephencrowell** [comment]
> * why not `http://localhost:4004` or `http://localhost:4004/hapi-fhir-jpaserver/fhir` or even `localhost:4004`

For the shorter two, I wasn't sure the if all FHIR servers have the same `/hapi-fhir-jpaserver/fhir` as part of the url or not. For the full url, in order to do pagination (the way I found to at least), the url for the client has to be `http://localhost:4004/hapi-fhir-jpaserver/` instead of the full url.

I think for now it may be have the users give just `http://localhost:4004` and then append `/hapi-fhir-jpaserver/fhir`.

**Comment by ebrahimebrahim** [comment]
> For the shorter two, I wasn't sure the if all FHIR servers have the same `/hapi-fhir-jpaserver/fhir` as part of the url or not

Makes a lot of sense, of course "hapi" wouldn't always occur, good poiint

> I think for now it may be have the users give just `http://localhost:4004` and then append `/hapi-fhir-jpaserver/fhir`.

No no the way you did it originally makes perfect sense now. Thanks for explaining

Let's just make it work regardless of whether the trailing slash is there
