### ISSUE TITLE
Re-organize and cleanup extension files

### ISSUE THREAD

**Issue by jcfr** [stephencrowell/SlicerEHRSandbox#7]
### Remove `__pycache__` directory

Directories like `FHIRReader/FHIRReader/__pycache__` should not be part of the project.

### Add `CMakeLists.txt` and module directory at the top-level

To follow established convention for Slicer extensions, consider having the `CMakeLists.txt` and module directory available in the top-level directory.

Instead of the following structure:

```
FHIRReader
FHIRReader/CMakeLists.txt
FHIRReader/FHIRReader
FHIRReader/FHIRReader/CMakeLists.txt
FHIRReader/FHIRReader/FHIRReader.py
FHIRReader/FHIRReader/Resources
FHIRReader/FHIRReader/Resources/Icons
FHIRReader/FHIRReader/Resources/Icons/FHIRReader.png
FHIRReader/FHIRReader/Resources/UI
FHIRReader/FHIRReader/Resources/UI/FHIRReader.ui
FHIRReader/FHIRReader/Testing
FHIRReader/FHIRReader/Testing/CMakeLists.txt
FHIRReader/FHIRReader/Testing/Python
FHIRReader/FHIRReader/Testing/Python/CMakeLists.txt
FHIRReader/FHIRReader.png
README.md
```

I suggest to re-organize files to have the following:

```
CMakeLists.txt
FHIRReader
FHIRReader/CMakeLists.txt
FHIRReader/FHIRReader.py
FHIRReader/Resources
FHIRReader/Resources/Icons
FHIRReader/Resources/Icons/FHIRReader.png
FHIRReader/Resources/UI
FHIRReader/Resources/UI/FHIRReader.ui
FHIRReader/Testing
FHIRReader/Testing/CMakeLists.txt
FHIRReader/Testing/Python
FHIRReader/Testing/Python/CMakeLists.txt
FHIRReader.png
README.md
```

Examples:
* https://github.com/SlicerRt/SlicerRT
* https://github.com/SlicerMorph/SlicerMorph

**Comment by ebrahimebrahim** [comment]
Also adding [github's premade gitignore for python](https://github.com/github/gitignore/blob/main/Python.gitignore) can help avoid accidentally tracking things like `__pycache__` in the future
